//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using ProjectManage.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoginEntities2 : DbContext
    {
        public LoginEntities2()
            : base("name=LoginEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<ProjectName> ProjectNames { get; set; }
        public DbSet<Files> Files { get; set; }
        public DbSet<Projects> Projects { get; set; }
        public DbSet<TagTypes> TagTypes { get; set; }
    }
}
